version = 0.1

[default.deploy.parameters]
stack_name = "comic-nova-backend"
resolve_s3 = true
s3_prefix = "comic-nova-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
